
### Get request with a header
GET http://localhost:8080/tasks
Accept: application/json

### Get request with a header
GET http://localhost:8080/tasks?from=2018-11-01
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Secc",
  "description": "Second Description",
  "finishTime": "01/12/2018 11:19"
}

###